# Generated by Django 5.2.7 on 2025-10-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar_url', models.URLField(blank=True)),
                ('syarat_poin', models.IntegerField(help_text='Poin minimum untuk mendapatkan lencana ini')),
            ],
        ),
        migrations.CreateModel(
            name='PertanyaanArena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('klasifikasi', 'Klasifikasi Komponen'), ('kartu_simbiosis', 'Duel Simbiosis'), ('cerita_predator', 'Jejak Predator')], max_length=20)),
                ('konten_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_benar', models.BooleanField()),
                ('waktu_jawab', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pertanyaanarena')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_poin', models.IntegerField(default=0)),
                ('lencana', models.ManyToManyField(blank=True, to='core.lencana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
