# Generated by Django 5.2.7 on 2025-10-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lencana_pertanyaanarena_jawabansiswa_profilsiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField()),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kuis')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('siswa', 'kuis')},
            },
        ),
    ]
