# Generated by Django 5.2.7 on 2025-10-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hasilkuis'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEkosistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi_singkat', models.TextField(max_length=200)),
                ('gambar_url', models.URLField(help_text='URL gambar dari internet', max_length=500)),
                ('kategori', models.CharField(choices=[('Fauna', 'Fauna'), ('Flora', 'Flora')], max_length=10)),
            ],
            options={
                'verbose_name': 'Info Ekosistem',
                'verbose_name_plural': 'Info Ekosistem',
            },
        ),
        migrations.AlterField(
            model_name='jawabansiswa',
            name='pertanyaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='core.pertanyaanarena'),
        ),
    ]
