# Generated by Django 5.2.7 on 2025-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quizattemptlog_usermateriprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='penjelasan',
            field=models.TextField(blank=True, help_text='Penjelasan mengapa jawaban ini benar (opsional).', null=True),
        ),
    ]
