# Generated by Django 5.2.7 on 2025-11-07 08:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pertanyaan_penjelasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='penjelasan',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Penjelasan mengapa jawaban ini benar (opsional).', null=True),
        ),
        migrations.AlterField(
            model_name='subtopik',
            name='konten',
            field=ckeditor.fields.RichTextField(help_text='Isi konten utama untuk sub-topik ini.'),
        ),
    ]
