# Generated by Django 5.2.7 on 2025-11-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pertanyaan_penjelasan_alter_subtopik_konten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopik',
            name='konten',
            field=models.TextField(help_text='Isi konten utama untuk sub-topik ini.'),
        ),
    ]
