# Generated by Django 5.2.7 on 2025-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_subtopik_konten'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilsiswa',
            name='total_waktu_akses',
            field=models.IntegerField(default=0, help_text='Total waktu akses dalam detik'),
        ),
    ]
